### PR TITLE
Add a recipe for handling the file uploads

### PR DESCRIPTION
**Pull request by barseghyanartur**
Add a recipe for handling the file uploads.

### CODE REVIEW

**Comment by vitalik** [comment]
Hi @barseghyanartur 

I think you can simplify saving:

```Python
from ninja import UploadedFile, File

@api.post("/employees")
def create_employee(request, payload: EmployeeIn, cv: UploadedFile = File(...)):
    payload_dict = payload.dict()
    employee = Employee(**payload_dict)
    employee.cv.save(cv.name, cv) # will save model instance as well
    return {"id": employee.id}
```

**Comment by barseghyanartur** [comment]
@vitalik:

Will do.

**Comment by vitalik** [comment]
> Shall I, perhaps, add a second recipe for when you don't work with models, but still want to upload files?

yes - makes sense

**Comment by barseghyanartur** [comment]
@vitalik:

Ready.

**Comment by vitalik** [comment]
Thank you

**Pull request merged**
