### PR TITLE
Made TestClient accept COOKIES + documentation

### PR DESCRIPTION
**Pull request by c4ffein**
Hello,

I just made the `TestClient` accept an optional `COOKIES` parameter, just like it was already possible to pass `headers`.
I also updated the documentation.

Thanks!

### CODE REVIEW

**Comment by vitalik** [comment]
Thank you

**Comment by laurent-brisbois** [comment]
@vitalik 
Any chance to see this change in a new release soon ?
Thanks in advance 🙏

**Comment by c4ffein** [comment]
@laurent-brisbois you may check [Django Shinobi](https://github.com/pmdevita/django-shinobi), the community fork that is currently maintained
The plan is to merge it back if possible, and if we have no news from @vitalik we will still make the framework more community oriented so the current situation doesn’t happen again

**Comment by laurent-brisbois** [comment]
> @laurent-brisbois you may check [Django Shinobi](https://github.com/pmdevita/django-shinobi), the community fork that is currently maintained
> The plan is to merge it back if possible, and if we have no news from @vitalik we will still make the framework more community oriented so the current situation doesn’t happen again

Okay thanks @c4ffein for the info. I'll have a look 🙏.

**Pull request merged**
