### PR TITLE
add haystck in django-ninja

### PR DESCRIPTION
**Pull request by sunboy123**
is there any solution for django-ninja use haystack? if not , i hope to you can integrated

### CODE REVIEW

**Comment by vitalik** [comment]
@sunboy123 there is something werid with your PR - there are like 187 files changed ?

**Comment by sunboy123** [comment]
@vitalik  no.  maybe i write the pr in wrong position. i just wanna to submit pr for adding haystack in ninja

**Comment by baseplate-admin** [comment]
Hi @sunboy123, 

Can you rebase your PR on top of `master`?

**Comment by sunboy123** [comment]
@baseplate-admin  ok,got it

**Pull request closed without merging**
