### PR TITLE
Docs restructure

### PR DESCRIPTION
**Pull request by SmileyChris**
The documentation has grown larger than the categorisation being used. I've moved the documents into a format that resembles the https://diataxis.fr/ framework ideals.

I've also rewritten the tutorial to a several step process, and created the start of some reference documentation.

There's still more work that could be done on it (obviously - docs are never really "done"), but I haven't removed anything that's in the current docs. Take a look, anyway!

### CODE REVIEW

**Comment by SmileyChris** [comment]
@vitalik I rebased against latest master, fixing conflicts and ensuring everything lives under the new layout (my recently merged temporal response docs aren't even in the current live docs index page, oops)

**Comment by SmileyChris** [comment]
Hey @vitalik -- I keep this branch updated, but if it's too big of a change or you don't like the direction I went in then just let me know so I can close the branch rather than updating it in futility ;)

**Comment by vitalik** [comment]
Hi @SmileyChris 

Yes, I like the structure
but most likely will improve the tutorial section

Thank you

**Comment by SmileyChris** [comment]
🥳 Yay for the merge!

I agree that the tutorial section can use some more love. Now with the better structure, it's easier to start thinking about the documentation in each section with a bit more purpose.

As the diataxis framework explains it:

documentiation sections

**Pull request merged**
