### PR TITLE
[`Enhancement`] : Add middleware for `PATCH` | `PUT` file upload

### LINKED ISSUE #716: [`Enhancement`] : Add file upload middleware to docs
**Is your feature request related to a problem? Please describe.**
 I'm always frustrated when  i cant upload files in `PATCH` method

**Describe the solution you'd like**
I want to contribute this fully functional type hinted async and sync middleware to the docs

```python
from django.utils.decorators import sync_and_async_middleware
from collections.abc import Callable
from django.http import HttpRequest, HttpResponse
from asgiref.sync import sync_to_async

import asyncio


@sync_and_async_middleware
def process_put_patch(get_response: Callable) -> Callable:
    if asyncio.iscoroutinefunction(get_response):

        async def middleware(request: HttpRequest) -> HttpResponse:
            if (
                request.method in ("PUT", "PATCH")
                and request.content_type != "application/json"
            ):
                initial_method = request.method
                request.method = "POST"
                request.META["REQUEST_METHOD"] = "POST"
                await sync_to_async(request._load_post_and_files)()
                request.META["REQUEST_METHOD"] = initial_method
                request.method = initial_method

            return await get_response(request)

    else:

        def middleware(request: HttpRequest) -> HttpResponse:
            if (
                request.method in ("PUT", "PATCH")
                and request.content_type != "application/json"
            ):
                initial_method = request.method
                request.method = "POST"
                request.META["REQUEST_METHOD"] = "POST"
                request._load_post_and_files()
                request.META["REQUEST_METHOD"] = initial_method
                request.method = initial_method

            return get_response(request)

    return middleware
```

### PR DESCRIPTION
**Pull request by baseplate-admin**
Closes #716

### CODE REVIEW

**Comment by baseplate-admin** [comment]
Hi @vitalik,

One small question. Does the test client support file upload?

```python
from ninja.testing import TestClient

client = TestClient(router)
```

**Comment by baseplate-admin** [comment]
Django 2 is EOL.

In my opinion we should target 3.1 and upwards

**Comment by baseplate-admin** [comment]
Hey @vitalik ,

I have skipped coverage on middleware as the middleware works as expected :)

**Comment by baseplate-admin** [comment]
merge this after #720

**Comment by baseplate-admin** [comment]
Hi @vitalik,

Due to the lack of input on this Pull Request i have made [`ninja-put-patch-file-upload-middleware`](https://pypi.org/project/ninja-put-patch-file-upload-middleware/)

Feel free to open this pull request again to continue the progress here.

Thank you again for creating `django-ninja` .

**Comment by jleclanche** [comment]
@vitalik I'd like to revive this a bit. I just spent over two hours banging my own head against this until finding out that this is an issue. There's no feedback from the library about it.

**Comment by jleclanche** [comment]
https://github.com/vitalik/django-ninja/issues/1059

**Pull request closed without merging**
