### PR TITLE
added methods for AsyncOperation

### PR DESCRIPTION
**Pull request by ETretyakov**
I have read this issue 44 (https://github.com/vitalik/django-ninja/issues/44), please explain what is needed to solve the issue, this fix is really necessary for our development.

### CODE REVIEW

**Comment by vitalik** [comment]
The main problem is that  you can combine both sync and async callbacks...

so you cannot just await all in a loop and need to determine if callback is async - then await it, otherwise run normally (and if in sync mode you got async authentication - need to run async_to_sync adapter)

**Comment by ETretyakov** [comment]
Do recent commits fix the problem?

**Comment by ETretyakov** [comment]
@vitalik sorry for pushing you, is there any hope to solve the issue?

**Comment by al-stefanitsky-mozdor** [comment]
Agreed with @vitalik, I think it should be separated logic for async and sync views. I mean that you should NOT use sync_to_async at all, and handle such cases outside from the regular Operation class, only in the AsyncOperation.

**Comment by stinovlas** [comment]
I just stumbled upon this when I was trying to create async auth for my API. It seems that right now, there is no way to have an async auth callback for the `NinjaAPI` or `Router` objects. Even the synchronous `django_auth` suggested in documentation does not work for my async views, because it accesses the database. That could be solved by decorating `django_auth` by `sync_to_async` if async auth callbacks were possible. Obviously, router can have both sync and async views and it needs to handle the authentication properly in both cases.

I'm willing to chip in and help this change to happen, but I'd need to know what's wrong with this PR and why it hasn't been moved forward.

**Pull request closed without merging**
