### PR TITLE
[`Docs`] : Run `isort`

### PR DESCRIPTION
**Pull request by baseplate-admin**
Hi @vitalik ,

It seems that isort was not run on docs folder. This Pull Request aims to fix that

### CODE REVIEW

**Comment by vitalik** [comment]
well, docs are meant to be more compact - now that you sorted - it made lot of gaps (and highlighted lines in markdown are now not matching)

**Comment by baseplate-admin** [comment]
> well, docs are meant to be more compact - now that you sorted - it made lot of gaps (and highlighted lines in markdown are now not matching)


Oops i will have a look

**Comment by vitalik** [comment]
@baseplate-admin well leave it - I do not see a point doing this in docs examples, as it will just blur readers attention, I prefer it to be more compact for reading

**Comment by baseplate-admin** [comment]
> @baseplate-admin well leave it - I do not see a point doing this in docs examples, as it will just blur readers attention, I prefer it to be more compact for reading

Fair enough

**Pull request closed without merging**
