### PR TITLE
Fix Paginated Schema default(example value)

### PR DESCRIPTION
**Pull request by esc5221**
This PR resolves Issue https://github.com/vitalik/django-ninja/issues/560
* Setting default value for `paginator.items_attribute` makes `items` schemas' example value not visible
* Removed default value of Output Schema

### Before
image</td>  </tr> </table> 

### After
image

### CODE REVIEW

**Comment by vitalik** [comment]
Hi @esc5221 would be able to add test cases that covers the issue you described ?

**Comment by esc5221** [comment]
added new test in `test_openapi_schema.py`,  and edited existing tests, as `PagedResponse` schema is added in the test scope.

**Comment by bpdev97** [comment]
@vitalik Do tests just need fixed for this to be merged?

**Comment by vitalik** [comment]
yes, looks like it's safe to merge if tests are working

**Comment by vitalik** [comment]
Merged in a separate PR

Thank you for contribution !

**Pull request closed without merging**
