### PR TITLE
Distinguish between AuthenticationError and AuthorizationError

### PR DESCRIPTION
**Pull request by c4ffein**
Implements #1218

### CODE REVIEW

**Comment by lordi** [comment]
As far as I'm concerned, this looks good, thx

**Comment by BlaiseMuhirwa** [comment]
Can we merge this soon? I also think it looks good and I need this distinction as well since I currently use `django-ninja`.

**Comment by vitalik** [comment]
I think this might be done better...


`AuthenticationError`, `AuthorizationError` should  be both inherited from HttpError (with corresponding codes and messages)

that way only one default http-error handler is needed (and users should be able to overwrite custom handlers for each class individualy)

**Comment by c4ffein** [comment]
> I think this might be done better...
> 
> `AuthenticationError`, `AuthorizationError` should be both inherited from HttpError (with corresponding codes and messages)
> 
> that way only one default http-error handler is needed (and users should be able to overwrite custom handlers for each class individualy)

Didn't want to cause too much changes with this PR, but definitely the way to go

**Comment by NikolozCh** [comment]
Hi, thanks for the updates. When are you guys expecting these changes? Release 1.3.0 doesn't contain AFAIK? Please, correct me if I am wrong. Thanks!

**Comment by c4ffein** [comment]
@NikolozCh you may check [Django Shinobi](https://github.com/pmdevita/django-shinobi), the community fork that is currently maintained
The plan is to merge it back if possible, and if we have no news from @vitalik we will still make the framework more community oriented so the current situation doesn’t happen again

**Comment by NikolozCh** [comment]
Thanks @c4ffein. Django Shinobi worked perfectly well.

**Pull request merged**
